#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
WORKDIR /inetpub/wwwroot
COPY ./Sources/KProcess.KL2.WebAdmin/bin/Release/PublishOutput .
ENTRYPOINT ["powershell.exe", "c:\\inetpub\\wwwroot\\PsScripts\\Startup.ps1"]

ENV DATASOURCE=.\SQLEXPRESS
ENV DATABASE=KProcess.KL2
ENV APISCHEME=http
ENV API=localhost
ENV APIPORT=8081
ENV FILESERVERSCHEME=http
ENV FILESERVER=localhost
ENV FILESERVERPORT=8082