//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KProcess.Ksmed.Server.Activation.KeygenApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KProcess.Ksmed.Server.Activation.KeygenApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;div dir=&quot;ltr&quot; style=&apos;font-size: 13px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;&apos;&gt;       
        ///    &lt;div&gt;
        ///        Hi {0},
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt;
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        We thank you for choosing Kl²®, our process analysis solution for optimisation and training purposes.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt; 
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        To download the installation package : &lt;a href=&quot;{1}&quot;&gt;click here&lt;/a&gt;.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;span style=&quot;font-size: 9pt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string mail_kl2_en {
            get {
                return ResourceManager.GetString("mail_kl2_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;div dir=&quot;ltr&quot; style=&apos;font-size: 13px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;&apos;&gt;       
        ///    &lt;div&gt;
        ///        Bonjour {0},
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt;
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        Nous vous remercions d’avoir choisi notre solution KL²® d’analyse de process pour l’optimisation et la formation.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt; 
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        Pour télécharger le package d’installation : &lt;a href=&quot;{1}&quot;&gt;cliquer ici&lt;/a&gt;.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;spa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string mail_kl2_fr {
            get {
                return ResourceManager.GetString("mail_kl2_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;div dir=&quot;ltr&quot; style=&apos;font-size: 13px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;&apos;&gt;       
        ///    &lt;div&gt;
        ///        Hi {0},
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt;
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        We thank you for using Kl²®, our process analysis solution for optimisation and training purposes.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt; 
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        To download the update package : &lt;a href=&quot;{1}&quot;&gt;click here&lt;/a&gt;.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;span style=&quot;font-size: 9pt;&quot;&gt;(ZIP fi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string mail_update_kl2_en {
            get {
                return ResourceManager.GetString("mail_update_kl2_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;div dir=&quot;ltr&quot; style=&apos;font-size: 13px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;&apos;&gt;       
        ///    &lt;div&gt;
        ///        Bonjour {0},
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt;
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        Nous vous remercions d&apos;utiliser notre solution KL²® d’analyse de process pour l’optimisation et la formation.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;br&gt; 
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        Pour télécharger le package de mise à jour : &lt;a href=&quot;{1}&quot;&gt;cliquer ici&lt;/a&gt;.
        ///    &lt;/div&gt; 
        ///    &lt;div&gt;
        ///        &lt;span st [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string mail_update_kl2_fr {
            get {
                return ResourceManager.GetString("mail_update_kl2_fr", resourceCulture);
            }
        }
    }
}
