//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class KAction : ITrackable, IMergeable
    {
        public KAction()
        {
            this.ActionsReduced = new List<KAction>();
            this.Ref2 = new List<Ref2Action>();
            this.Ref4 = new List<Ref4Action>();
            this.Ref5 = new List<Ref5Action>();
            this.Ref6 = new List<Ref6Action>();
            this.Ref7 = new List<Ref7Action>();
            this.Ref3 = new List<Ref3Action>();
            this.Ref1 = new List<Ref1Action>();
            this.Successors = new List<KAction>();
            this.Predecessors = new List<KAction>();
        }
    
        public int ActionId { get; set; }
        public int ScenarioId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> OriginalActionId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public string WBS { get; set; }
        public string Label { get; set; }
        public long Start { get; set; }
        public long Finish { get; set; }
        public long BuildStart { get; set; }
        public long BuildFinish { get; set; }
        public bool IsRandom { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public Nullable<decimal> CustomNumericValue { get; set; }
        public Nullable<decimal> CustomNumericValue2 { get; set; }
        public Nullable<decimal> CustomNumericValue3 { get; set; }
        public Nullable<decimal> CustomNumericValue4 { get; set; }
        public string CustomTextValue { get; set; }
        public string CustomTextValue2 { get; set; }
        public string CustomTextValue3 { get; set; }
        public string CustomTextValue4 { get; set; }
        public string DifferenceReason { get; set; }
        public byte[] Thumbnail { get; set; }
        public bool IsThumbnailSpecific { get; set; }
        public Nullable<long> ThumbnailPosition { get; set; }
        public byte[] RowVersion { get; set; }
    
        public ActionCategory Category { get; set; }
        public ICollection<KAction> ActionsReduced { get; set; }
        public KAction Original { get; set; }
        public Resource Resource { get; set; }
        public Scenario Scenario { get; set; }
        public User Creator { get; set; }
        public User LastModifier { get; set; }
        public Video Video { get; set; }
        public KActionReduced Reduced { get; set; }
        public ICollection<Ref2Action> Ref2 { get; set; }
        public ICollection<Ref4Action> Ref4 { get; set; }
        public ICollection<Ref5Action> Ref5 { get; set; }
        public ICollection<Ref6Action> Ref6 { get; set; }
        public ICollection<Ref7Action> Ref7 { get; set; }
        public ICollection<Ref3Action> Ref3 { get; set; }
        public ICollection<Ref1Action> Ref1 { get; set; }
        public ICollection<KAction> Successors { get; set; }
        public ICollection<KAction> Predecessors { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
