//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class KActionReduced : ITrackable, IMergeable
    {
        public int ActionId { get; set; }
        public string ActionTypeCode { get; set; }
        public string Solution { get; set; }
        public double ReductionRatio { get; set; }
        public long OriginalBuildDuration { get; set; }
        public byte[] RowVersion { get; set; }
    
        public KAction Action { get; set; }
        public ActionType ActionType { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
