//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class Publication : ITrackable, IMergeable
    {
        public Publication()
        {
            this.PublishedActions = new List<PublishedAction>();
        }
    
        public System.Guid PublicationId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ScenarioId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public long CriticalPathIDuration { get; set; }
        public int PublishedByUserId { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string Watermark { get; set; }
        public int MinDurationVideo { get; set; }
        public string Disposition { get; set; }
        public int ProcessId { get; set; }
    
        public Project Project { get; set; }
        public Scenario Scenario { get; set; }
        public User Publisher { get; set; }
        public ICollection<PublishedAction> PublishedActions { get; set; }
        public Procedure Process { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
