//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class PublishedAction : ITrackable, IMergeable
    {
        public PublishedAction()
        {
            this.PublishedReferentialActions = new List<PublishedReferentialAction>();
        }
    
        public int PublishedActionId { get; set; }
        public System.Guid PublicationId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> ActionCategoryId { get; set; }
        public string WBS { get; set; }
        public string Label { get; set; }
        public long Start { get; set; }
        public long Finish { get; set; }
        public long BuildStart { get; set; }
        public long BuildFinish { get; set; }
        public bool IsRandom { get; set; }
        public Nullable<decimal> CustomNumericValue { get; set; }
        public Nullable<decimal> CustomNumericValue2 { get; set; }
        public Nullable<decimal> CustomNumericValue3 { get; set; }
        public Nullable<decimal> CustomNumericValue4 { get; set; }
        public string CustomTextValue { get; set; }
        public string CustomTextValue2 { get; set; }
        public string CustomTextValue3 { get; set; }
        public string CustomTextValue4 { get; set; }
        public string DifferenceReason { get; set; }
        public string ThumbnailHash { get; set; }
        public string CutVideoHash { get; set; }
    
        public Publication Publication { get; set; }
        public PublishedActionCategory PublishedActionCategory { get; set; }
        public PublishedResource PublishedResource { get; set; }
        public ICollection<PublishedReferentialAction> PublishedReferentialActions { get; set; }
        public CutVideo CutVideo { get; set; }
        public PublishedFile Thumbnail { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
