//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class PublishedFile : ITrackable, IMergeable
    {
        public PublishedFile()
        {
            this.PublishedActionCategories = new List<PublishedActionCategory>();
            this.PublishedReferentials = new List<PublishedReferential>();
            this.PublishedResources = new List<PublishedResource>();
            this.PublishedActions = new List<PublishedAction>();
        }
    
        public string Hash { get; set; }
        public string Extension { get; set; }
    
        public ICollection<PublishedActionCategory> PublishedActionCategories { get; set; }
        public ICollection<PublishedReferential> PublishedReferentials { get; set; }
        public ICollection<PublishedResource> PublishedResources { get; set; }
        public ICollection<PublishedAction> PublishedActions { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
