//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class ScenarioState : ITrackable, IMergeable
    {
        public ScenarioState()
        {
            this.Scenarios = new List<Scenario>();
        }
    
        public string ScenarioStateCode { get; set; }
        public int ShortLabelResourceId { get; set; }
        public int LongLabelResourceId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public AppResourceKey LongLabelResource { get; set; }
        public AppResourceKey ShortLabelResource { get; set; }
        public ICollection<Scenario> Scenarios { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
