//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class Scenario : ITrackable, IMergeable
    {
        public Scenario()
        {
            this.Actions = new List<KAction>();
            this.InheritedScenarios = new List<Scenario>();
            this.Solutions = new List<Solution>();
            this.Publications = new List<Publication>();
        }
    
        public int ScenarioId { get; set; }
        public int ProjectId { get; set; }
        public string StateCode { get; set; }
        public string NatureCode { get; set; }
        public Nullable<int> OriginalScenarioId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public bool IsShownInSummary { get; set; }
        public long CriticalPathIDuration { get; set; }
        public Nullable<System.Guid> WebPublicationGuid { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public ICollection<KAction> Actions { get; set; }
        public Project Project { get; set; }
        public ICollection<Scenario> InheritedScenarios { get; set; }
        public Scenario Original { get; set; }
        public ScenarioNature Nature { get; set; }
        public ScenarioState State { get; set; }
        public User Creator { get; set; }
        public User LastModifier { get; set; }
        public ICollection<Solution> Solutions { get; set; }
        public ICollection<Publication> Publications { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
