//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class User : ITrackable, IMergeable
    {
        public User()
        {
            this.CreatedActions = new List<KAction>();
            this.LastModifiedActions = new List<KAction>();
            this.CreatedAppResourceValues = new List<AppResourceValue>();
            this.LastModifiedAppResourceValues = new List<AppResourceValue>();
            this.CreatedProjects = new List<Project>();
            this.LastModifiedProjects = new List<Project>();
            this.CreatedRefs1 = new List<Ref1>();
            this.LastModifiedRefs1 = new List<Ref1>();
            this.CreatedRefs2 = new List<Ref2>();
            this.LastModifiedRefs2 = new List<Ref2>();
            this.CreatedRefs3 = new List<Ref3>();
            this.LastModifiedRefs3 = new List<Ref3>();
            this.CreatedRefs4 = new List<Ref4>();
            this.LastModifiedRefs4 = new List<Ref4>();
            this.CreatedRefs5 = new List<Ref5>();
            this.LastModifiedRefs5 = new List<Ref5>();
            this.CreatedRefs6 = new List<Ref6>();
            this.LastModifiedRefs6 = new List<Ref6>();
            this.CreatedRefs7 = new List<Ref7>();
            this.LastModifiedRefs7 = new List<Ref7>();
            this.CreatedActionCategories = new List<ActionCategory>();
            this.LastModifiedActionCategories = new List<ActionCategory>();
            this.CreatedResources = new List<Resource>();
            this.LastModifiedResources = new List<Resource>();
            this.CreatedScenarios = new List<Scenario>();
            this.LastModifiedScenarios = new List<Scenario>();
            this.CreatedUsers = new List<User>();
            this.LastModifiedUsers = new List<User>();
            this.UserRoleProjects = new List<UserRoleProject>();
            this.CreatedVideos = new List<Video>();
            this.LastModifiedVideos = new List<Video>();
            this.Roles = new List<Role>();
            this.Publication = new List<Publication>();
            this.Teams = new List<Team>();
        }
    
        public int UserId { get; set; }
        public string DefaultLanguageCode { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string Firstname { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public ICollection<KAction> CreatedActions { get; set; }
        public ICollection<KAction> LastModifiedActions { get; set; }
        public ICollection<AppResourceValue> CreatedAppResourceValues { get; set; }
        public ICollection<AppResourceValue> LastModifiedAppResourceValues { get; set; }
        public Language DefaultLanguage { get; set; }
        public ICollection<Project> CreatedProjects { get; set; }
        public ICollection<Project> LastModifiedProjects { get; set; }
        public ICollection<Ref1> CreatedRefs1 { get; set; }
        public ICollection<Ref1> LastModifiedRefs1 { get; set; }
        public ICollection<Ref2> CreatedRefs2 { get; set; }
        public ICollection<Ref2> LastModifiedRefs2 { get; set; }
        public ICollection<Ref3> CreatedRefs3 { get; set; }
        public ICollection<Ref3> LastModifiedRefs3 { get; set; }
        public ICollection<Ref4> CreatedRefs4 { get; set; }
        public ICollection<Ref4> LastModifiedRefs4 { get; set; }
        public ICollection<Ref5> CreatedRefs5 { get; set; }
        public ICollection<Ref5> LastModifiedRefs5 { get; set; }
        public ICollection<Ref6> CreatedRefs6 { get; set; }
        public ICollection<Ref6> LastModifiedRefs6 { get; set; }
        public ICollection<Ref7> CreatedRefs7 { get; set; }
        public ICollection<Ref7> LastModifiedRefs7 { get; set; }
        public ICollection<ActionCategory> CreatedActionCategories { get; set; }
        public ICollection<ActionCategory> LastModifiedActionCategories { get; set; }
        public ICollection<Resource> CreatedResources { get; set; }
        public ICollection<Resource> LastModifiedResources { get; set; }
        public ICollection<Scenario> CreatedScenarios { get; set; }
        public ICollection<Scenario> LastModifiedScenarios { get; set; }
        public ICollection<User> CreatedUsers { get; set; }
        public User Creator { get; set; }
        public ICollection<User> LastModifiedUsers { get; set; }
        public User LastModifier { get; set; }
        public ICollection<UserRoleProject> UserRoleProjects { get; set; }
        public ICollection<Video> CreatedVideos { get; set; }
        public ICollection<Video> LastModifiedVideos { get; set; }
        public ICollection<Role> Roles { get; set; }
        public ICollection<Publication> Publication { get; set; }
        public ICollection<Team> Teams { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
