//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kprocess.KL2.Models
{
    using System;
    using System.Collections.Generic;
    using TrackableEntities;
    
    public partial class Video : ITrackable, IMergeable
    {
        public Video()
        {
            this.Actions = new List<KAction>();
        }
    
        public int VideoId { get; set; }
        public int ProjectId { get; set; }
        public string NatureCode { get; set; }
        public Nullable<int> DefaultResourceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Duration { get; set; }
        public string Format { get; set; }
        public string FilePath { get; set; }
        public System.DateTime ShootingDate { get; set; }
        public byte[] Thumbnail { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ModifiedByUserId { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public ICollection<KAction> Actions { get; set; }
        public Project Project { get; set; }
        public Resource DefaultResource { get; set; }
        public User Creator { get; set; }
        public User LastModifier { get; set; }
        public VideoNature Nature { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }
}
