//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KProcess.Ksmed.Ext.Kprocess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KProcess.Ksmed.Ext.Kprocess.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin vers le répertoire d&apos;export par défaut du fichier excel.
        /// </summary>
        internal static string ExtKp_ConfigurationView_DefaultExportDirectory {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_DefaultExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin vers le répertoire d&apos;export par défaut des vidéos découpées.
        /// </summary>
        internal static string ExtKp_ConfigurationView_DefaultExportVideoDirectory {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_DefaultExportVideoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquer le nom du fichier Excel.
        /// </summary>
        internal static string ExtKp_ConfigurationView_ExcelFileNameMarkingIsEnabled {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_ExcelFileNameMarkingIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string ExtKp_ConfigurationView_ExportExcel {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin vers le fichier modèle .
        /// </summary>
        internal static string ExtKp_ConfigurationView_ExportExcelModelPath {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_ExportExcelModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur des groupes d&apos;action.
        /// </summary>
        internal static string ExtKp_ConfigurationView_GanttGroupColor {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_GanttGroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gantt.
        /// </summary>
        internal static string ExtKp_ConfigurationView_GantTitle {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_GantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur des actions sans catégorie associée.
        /// </summary>
        internal static string ExtKp_ConfigurationView_GanttNoCategoryColor {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_GanttNoCategoryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur des tâches &quot;importantes&quot;.
        /// </summary>
        internal static string ExtKp_ConfigurationView_ImportantTaskColor {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_ImportantTaskColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum d&apos;images par ligne pour un référentiel dans le détail des tâches.
        /// </summary>
        internal static string ExtKp_ConfigurationView_MaxNumberActionRefImagePerCell {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_MaxNumberActionRefImagePerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum d&apos;images par ligne pour un référentiel dans la page de synthèse.
        /// </summary>
        internal static string ExtKp_ConfigurationView_MaxNumberScenarioRefImagesPerCell {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_MaxNumberScenarioRefImagesPerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise en forme.
        /// </summary>
        internal static string ExtKp_ConfigurationView_MEFTitle {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_MEFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser le multithreading (nécessite une grande capacité de processeur).
        /// </summary>
        internal static string ExtKp_ConfigurationView_Multithreading {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_Multithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte de marquage des vidéos découpées.
        /// </summary>
        internal static string ExtKp_ConfigurationView_OverlayTextVideo {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_OverlayTextVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Découpage et ré-encodage des vidéos.
        /// </summary>
        internal static string ExtKp_ConfigurationView_VideoEncodingTitle {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_VideoEncodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le marquage des vidéos découpées.
        /// </summary>
        internal static string ExtKp_ConfigurationView_VideoMarkingEnable {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_VideoMarkingEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquer le numéro WBS.
        /// </summary>
        internal static string ExtKp_ConfigurationView_WBSMarkingIsEnabled {
            get {
                return ResourceManager.GetString("ExtKp_ConfigurationView_WBSMarkingIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin vers le modèle de fichier n&apos;a pas été configuré..
        /// </summary>
        internal static string ExtKp_Error_MustConfigure {
            get {
                return ResourceManager.GetString("ExtKp_Error_MustConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du projet ne doit pas être vide..
        /// </summary>
        internal static string ExtKp_Error_MustContainDash {
            get {
                return ResourceManager.GetString("ExtKp_Error_MustContainDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publier le scénario sélectionné. Il est recommandé de fermer MS Excel au préalable..
        /// </summary>
        internal static string ExtKp_Export_Label {
            get {
                return ResourceManager.GetString("ExtKp_Export_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Export.
        /// </summary>
        internal static string ExtKp_Label {
            get {
                return ResourceManager.GetString("ExtKp_Label", resourceCulture);
            }
        }
    }
}
